name: crypto_monitoring

services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:4-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  postgres:
    container_name: postgres
    image: postgres:17
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongo:
    container_name: mongo
    image: mongo:7.0
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo_data:/data/db

  redis:
    container_name: redis
    image: redis:8.2-rc1
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  data_generator_service:
    container_name: data_generator_service
    build:
      context: .
      dockerfile: src/CryptoMonitoring.DataGenerator/CryptoMonitoring.DataGenerator.Presentation/Dockerfile
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
    depends_on:
      postgres:
        condition: service_started

  data_processor_service:
    container_name: data_processor_service
    build:
      context: ./src/CryptoMonitoring.DataProcessor
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}

  notification_service:
    container_name: notification_service
    build:
      context: ./src/CryptoMonitoring.NotificationService
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}

  report_generator_service:
    container_name: report_generator_service
    build:
      context: ./src/CryptoMonitoring.ReportGenerator
      dockerfile: Dockerfile
    ports:
      - "8083:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}

volumes:
  postgres_data:
  mongo_data:
  redis_data:
  rabbitmq_data: