// <auto-generated />
using System;
using CryptoMonitoring.DataGenerator.Persistence.Databases;
using CryptoMonitoring.Models.Enums;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CryptoMonitoring.DataGenerator.Persistence.Migrations
{
    [DbContext(typeof(CryptoMonitoringDataDbContext))]
    [Migration("20250716160138_AddUniqueIndexOfNameInCryptoCurrencyModel")]
    partial class AddUniqueIndexOfNameInCryptoCurrencyModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "indicator_type_enum", new[] { "bollinger_bands", "ema", "macd", "rsi", "sma" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CryptoMonitoring.Models.Entities.CryptoCurrency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("symbol");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("crypto_currencies", (string)null);
                });

            modelBuilder.Entity("CryptoMonitoring.Models.Entities.MarketData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal?>("Change24hPercent")
                        .HasColumnType("decimal")
                        .HasColumnName("сhange_24h_зercent");

                    b.Property<decimal?>("CirculatingSupply")
                        .HasColumnType("decimal")
                        .HasColumnName("circulating_supply");

                    b.Property<Guid>("CryptoCurrencyId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("MarketCapUsd")
                        .HasColumnType("decimal")
                        .HasColumnName("market_cap_usd");

                    b.Property<decimal>("PriceUsd")
                        .HasColumnType("decimal(100)")
                        .HasColumnName("price_usd");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<decimal>("Volume24hUsd")
                        .HasColumnType("decimal")
                        .HasColumnName("volume_24h_usd");

                    b.Property<decimal?>("Vwap24hUsd")
                        .HasColumnType("decimal")
                        .HasColumnName("vwap_24h_usd");

                    b.HasKey("Id");

                    b.HasIndex("CryptoCurrencyId", "Timestamp")
                        .IsUnique();

                    b.ToTable("market_datas", (string)null);
                });

            modelBuilder.Entity("CryptoMonitoring.Models.Entities.TechnicalIndicator", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CryptoCurrencyId")
                        .HasColumnType("uuid");

                    b.Property<IndicatorTypeEnum>("IndicatorType")
                        .HasColumnType("indicator_type_enum")
                        .HasColumnName("indicator_type");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("CryptoCurrencyId", "IndicatorType", "Timestamp")
                        .IsUnique();

                    b.ToTable("technical_indicators", (string)null);
                });

            modelBuilder.Entity("CryptoMonitoring.Models.Entities.MarketData", b =>
                {
                    b.HasOne("CryptoMonitoring.Models.Entities.CryptoCurrency", "CryptoCurrency")
                        .WithMany()
                        .HasForeignKey("CryptoCurrencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CryptoCurrency");
                });

            modelBuilder.Entity("CryptoMonitoring.Models.Entities.TechnicalIndicator", b =>
                {
                    b.HasOne("CryptoMonitoring.Models.Entities.CryptoCurrency", "CryptoCurrency")
                        .WithMany()
                        .HasForeignKey("CryptoCurrencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CryptoCurrency");
                });
#pragma warning restore 612, 618
        }
    }
}
